# Generated by Django 4.2.20 on 2025-04-21 12:00

from django.db import migrations

def populate_plans(apps, schema_editor):
    Plan = apps.get_model('core', 'Plan')
    
    # Create Free Plan - no price, no stripe ID, not shown on frontend
    Plan.objects.create(
        name='Free Plan',
        price_per_month=0.00,
        description='Basic free plan',
        ad_variations_per_month=1,
        stripe_price_id='',
        credits_price=19.88,
        show_on_frontend=False
    )
    
    # Create Growth Plan - $497/month with stripe price ID
    Plan.objects.create(
        name='Growth Plan',
        price_per_month=497.00,
        description='$497 /Month',
        ad_variations_per_month=25 ,
        stripe_price_id='price_1RGKLPB13B1g6neBYmmpdXHq',
        credits_price=19.88,
        show_on_frontend=True
    )
    
    # Create Pro Plan - $997/month with stripe price ID
    Plan.objects.create(
        name='Pro Plan',
        price_per_month=997.00,
        description='$997 /Month',
        ad_variations_per_month=60 ,
        stripe_price_id='price_1RGKM0B13B1g6neBaqZKzxpP',
        credits_price=16.62,
        show_on_frontend=True
    )

def reverse_populate_plans(apps, schema_editor):
    Plan = apps.get_model('core', 'Plan')
    Plan.objects.filter(name='Free Plan').delete()
    Plan.objects.filter(name='Growth Plan').delete()
    Plan.objects.filter(name='Pro Plan').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userasset'),
    ]

    operations = [
        migrations.RunPython(populate_plans, reverse_populate_plans),
    ]