# Generated by Django 4.2.20 on 2025-04-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_populate_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='unused_credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
