# Generated by Django 4.2.20 on 2025-05-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_subscription_unused_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='css_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
