# Generated by Django 4.2.20 on 2025-04-21 12:00

from django.db import migrations

def populate_transitions(apps, schema_editor):
    Transition = apps.get_model('core', 'Transitions')
    
    transitions_data = [
        {
            "name": "Crossfade",
            "duration": 0.2,
            "slug": "xfade"
        },
        {
            "name": "Fade In/Out",
            "duration": 0.1,
            "slug": "fade"
        },
        {
            "name": "Slide Left",
            "duration": 0.3,
            "slug": "slideleft"
        },
        {
            "name": "Slide Right",
            "duration": 0.3,
            "slug": "slideright"
        },
        {
            "name": "Wipe Left",
            "duration": 0.3,
            "slug": "wipeleft"
        },
        {
            "name": "Wipe Right",
            "duration": 0.3,
            "slug": "wiperight"
        },
        {
            "name": "Zoom",
            "duration": 0.3,
            "slug": "zoomin"
        }
    ]
    
    for transition_data in transitions_data:
        Transition.objects.create(**transition_data)

def reverse_populate_transitions(apps, schema_editor):
    Transition = apps.get_model('core', 'Transitions')
    Transition.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_transitions'),
    ]

    operations = [
        migrations.RunPython(populate_transitions, reverse_populate_transitions),
    ]