# Generated by Django 4.2.22 on 2025-06-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_populate_transition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitions',
            name='duration',
            field=models.FloatField(default=1.0),
        ),
    ]
