# Generated by Django 4.2.23 on 2025-08-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_populate_migrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundEffects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('audio_file', models.FileField(upload_to='soundeffects/')),
            ],
        ),
    ]
