# Generated by Django 4.2.20 on 2025-03-26 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('audio_file', models.FileField(null=True, upload_to='audio_files/')),
                ('video_file', models.FileField(null=True, upload_to='clips/')),
                ('srt_file', models.FileField(null=True, upload_to='clip_srt_files/')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.FileField(null=True, upload_to='output/')),
                ('text_file', models.FileField(null=True, upload_to='text_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subclip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('text', models.TextField()),
                ('audio_file', models.FileField(null=True, upload_to='audio_files/')),
                ('video_file', models.FileField(null=True, upload_to='subclips/')),
                ('srt_file', models.FileField(null=True, upload_to='subclip_srt_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processors.clips')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clips',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processors.video'),
        ),
        migrations.CreateModel(
            name='BackgroundMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='bg_music/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processors.video')),
            ],
        ),
    ]
