# Generated by Django 4.2.20 on 2025-03-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clips',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='backgroundmusic',
            name='end_time',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backgroundmusic',
            name='start_time',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='audio_file',
            field=models.FileField(default=1, upload_to='audio_files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='text_file',
            field=models.FileField(default=1, upload_to='text_files/'),
            preserve_default=False,
        ),
    ]
