# Generated by Django 4.2.20 on 2025-03-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0002_remove_clips_audio_file_backgroundmusic_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='audio_file',
            field=models.FileField(null=True, upload_to='audio_files/'),
        ),
    ]
