# Generated by Django 4.2.20 on 2025-03-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0004_alter_video_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='output',
            field=models.FileField(blank=True, null=True, upload_to='output/'),
        ),
    ]
