# Generated by Django 4.2.20 on 2025-03-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0006_alter_clips_srt_file_alter_clips_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='srt_file',
            field=models.FileField(blank=True, null=True, upload_to='srt_files/'),
        ),
    ]
