# Generated by Django 4.2.20 on 2025-03-27 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_populate_fonts'),
        ('processors', '0008_video_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtitle_font',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.font'),
        ),
    ]
