# Generated by Django 4.2.20 on 2025-03-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0009_video_subtitle_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clips',
            name='end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clips',
            name='start_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
