# Generated by Django 4.2.20 on 2025-03-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0010_alter_clips_end_time_alter_clips_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clips',
            name='srt_file',
        ),
        migrations.RemoveField(
            model_name='subclip',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='subclip',
            name='srt_file',
        ),
        migrations.AlterField(
            model_name='clips',
            name='end_time',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clips',
            name='start_time',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subclip',
            name='end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subclip',
            name='start_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
