# Generated by Django 4.2.20 on 2025-03-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0011_remove_clips_srt_file_remove_subclip_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clips',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='subclip',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='clips',
            name='video_end_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
