# Generated by Django 4.2.20 on 2025-03-29 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processors', '0012_alter_clips_options_alter_subclip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='box_roundness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='font_color',
            field=models.CharField(default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='font_size',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
