# Generated by Django 4.2.20 on 2025-03-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0013_video_box_roundness_video_font_color_video_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='elevenlabs_api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='voice_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
