# Generated by Django 4.2.20 on 2025-04-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0015_processingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='text_files/'),
        ),
    ]
