# Generated by Django 4.2.20 on 2025-04-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0016_alter_video_text_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='clips',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
