# Generated by Django 4.2.20 on 2025-04-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0017_clips_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtitle_box_color',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
