# Generated by Django 4.2.20 on 2025-04-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0018_video_subtitle_box_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='font_color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='subtitle_box_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
