# Generated by Django 4.2.20 on 2025-04-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0019_alter_video_font_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundmusic',
            name='volumn',
            field=models.FloatField(default=0.5),
        ),
    ]
