# Generated by Django 4.2.20 on 2025-04-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0020_backgroundmusic_volumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='output_with_bg',
            field=models.FileField(blank=True, null=True, upload_to='output_bg/'),
        ),
    ]
