# Generated by Django 4.2.20 on 2025-04-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0022_alter_video_box_roundness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clips',
            name='start_time',
            field=models.FloatField(default=0),
        ),
    ]
