# Generated by Django 4.2.20 on 2025-04-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0023_alter_clips_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clips',
            options={'ordering': ['sequence', 'start_time']},
        ),
        migrations.AlterField(
            model_name='clips',
            name='end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clips',
            name='start_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
