# Generated by Django 4.2.20 on 2025-05-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0024_alter_clips_options_alter_clips_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='output_with_bg_watermark',
            field=models.FileField(blank=True, null=True, upload_to='output_bg_watermark/'),
        ),
        migrations.AddField(
            model_name='video',
            name='output_with_watermark',
            field=models.FileField(blank=True, null=True, upload_to='output_watermark/'),
        ),
    ]
