# Generated by Django 4.2.20 on 2025-05-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0025_video_content_video_output_with_bg_watermark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clips',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
    ]
