# Generated by Django 4.2.20 on 2025-05-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0026_clips_is_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
