# Generated by Django 4.2.20 on 2025-05-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0027_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
