# Generated by Django 4.2.20 on 2025-05-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0028_alter_video_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclip',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
