# Generated by Django 4.2.20 on 2025-05-27 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0029_subclip_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subclip',
            name='sequence',
        ),
    ]
