# Generated by Django 4.2.22 on 2025-06-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0030_remove_subclip_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='history_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
