# Generated by Django 4.2.22 on 2025-06-10 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processors', '0031_video_history_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceoverSplitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.CharField(max_length=255)),
                ('original_text', models.TextField()),
                ('cleaned_text', models.TextField()),
                ('split_positions', models.JSONField(default=list)),
                ('segments', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_histories', to='processors.video')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'history_id')},
            },
        ),
    ]
