# Generated by Django 4.2.22 on 2025-06-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0032_voiceoversplithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='history_preview_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='VoiceoverSplitHistory',
        ),
    ]
