# Generated by Django 4.2.22 on 2025-06-10 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0033_video_history_preview_html_and_more'),
    ]

    operations = [
    ]
