# Generated by Django 4.2.22 on 2025-06-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0034_rename_history_preview_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='split_positions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
