# Generated by Django 4.2.22 on 2025-06-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0035_video_preview_text_video_split_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclip',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
    ]
