# Generated by Django 4.2.22 on 2025-06-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0037_subclip_asset_folder_subclip_asset_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subclip',
            name='asset_folder',
        ),
        migrations.RemoveField(
            model_name='subclip',
            name='asset_key',
        ),
        migrations.RemoveField(
            model_name='subclip',
            name='is_asset',
        ),
        migrations.RemoveField(
            model_name='subclip',
            name='is_image',
        ),
    ]
