# Generated by Django 4.2.22 on 2025-06-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0038_remove_subclip_asset_folder_remove_subclip_asset_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclip',
            name='asset_folder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subclip',
            name='asset_video_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subclip',
            name='assignment_type',
            field=models.CharField(blank=True, choices=[('upload', 'Upload'), ('asset', 'Asset')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subclip',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
