# Generated by Django 4.2.22 on 2025-06-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0039_subclip_asset_folder_name_subclip_asset_video_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subclip',
            name='asset_folder_name',
        ),
        migrations.RemoveField(
            model_name='subclip',
            name='asset_video_key',
        ),
        migrations.RemoveField(
            model_name='subclip',
            name='assignment_type',
        ),
        migrations.RemoveField(
            model_name='subclip',
            name='original_file_name',
        ),
    ]
