# Generated by Django 4.2.22 on 2025-06-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0040_remove_subclip_asset_folder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='asset_selection_history',
            field=models.JSONField(blank=True, default=list, help_text='Stores recent asset selections for quick access'),
        ),
        migrations.AddField(
            model_name='video',
            name='highlighted_texts',
            field=models.JSONField(blank=True, default=dict, help_text='Stores highlighted text assignments in format: {slide_id: {text: highlight_data}}'),
        ),
    ]
