# Generated by Django 4.2.22 on 2025-06-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0041_video_asset_selection_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='asset_selection_history',
        ),
        migrations.RemoveField(
            model_name='video',
            name='highlighted_texts',
        ),
    ]
