# Generated by Django 4.2.22 on 2025-06-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0042_remove_video_asset_selection_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclip',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
    ]
