# Generated by Django 4.2.23 on 2025-06-28 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0043_subclip_is_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_file', models.FileField(blank=True, null=True, upload_to='logs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='processors.video')),
            ],
        ),
    ]
