# Generated by Django 4.2.23 on 2025-07-05 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_transitions_duration'),
        ('processors', '0044_videologs'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclip',
            name='transition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subclips', to='core.transitions'),
        ),
    ]
