# Generated by Django 4.2.23 on 2025-07-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0045_subclip_transition'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclip',
            name='set_transition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subclip',
            name='transition_end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subclip',
            name='transition_start_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
