# Generated by Django 4.2.23 on 2025-07-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0046_subclip_set_transition_subclip_transition_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='elevenlabs_alignment_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
