# Generated by Django 4.2.23 on 2025-07-13 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_transitions_duration'),
        ('processors', '0047_video_elevenlabs_alignment_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='clips',
            name='transition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='core.transitions'),
        ),
    ]
