# Generated by Django 4.2.23 on 2025-08-03 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_soundeffects'),
        ('processors', '0048_clips_transition'),
    ]

    operations = [
        migrations.AddField(
            model_name='clips',
            name='sound_effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='core.soundeffects'),
        ),
    ]
