# Generated by Django 4.2.23 on 2025-08-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0049_clips_sound_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtitle_box_alpha',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
