# Generated by Django 4.2.23 on 2025-08-16 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_soundeffects'),
        ('processors', '0051_video_subtitle_box_alpha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clips',
            name='sound_effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='core.soundeffects'),
        ),
        migrations.AlterField(
            model_name='clips',
            name='transition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='core.transitions'),
        ),
    ]
